name: Update Shadowsocks-Rust

on:
  workflow_dispatch:
#  schedule:
#    - cron: 30 21 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set git identity
      run : |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Check up Shadowsocks-Rust VERSION
      run: |
        TAG_INFO="$(curl -H "Authorization: $GITHUB_TOKEN" -sL "https://api.github.com/repos/shadowsocks/shadowsocks-rust/releases/latest")"
        [ -n "$TAG_INFO" ] || exit 1
        VERSION="$(jq -r ".tag_name" <<< "$TAG_INFO" | tr -d 'v')" >> $GITHUB_ENV
        PKG_VERSION="$(awk -F "PKG_VERSION:=" '{print $2}' "$GITHUB_WORKSPACE/Makefile" | xargs)" >> $GITHUB_ENV
        echo "Shadowsocks-Rust Local version: $PKG_VERSION, Latest version: $VERSION" 
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV

    - name: Push Commits
      if: env.VERSION != env.PKG_VERSION
      run: |
        for i in $(jq -r '.assets[].browser_download_url | select(contains("musl") and contains("sha256"))' <<< "$TAG_INFO"); do
        	arch="$(awk -F '[-.]' '{print $9}' <<< "$i")"
        	libc="$(awk -F '[-.]' '{print $12}' <<< "$i" | tr -d 'musl')"
        	line="$(awk "/PKG_SOURCE:=.*\.$arch-.*$libc\./ {print NR}" "$GITHUB_WORKSPACE/Makefile")"
        	[ -n "$line" ] || continue
        	sha256="$(curl -fsSL "$i" | awk '{print $1}')" || exit 1
        	sed -i "$((line + 1))s/PKG_HASH:=.*/PKG_HASH:=$sha256/" "$GITHUB_WORKSPACE/Makefile"
        done
        sed -i "s,PKG_VERSION:=.*,PKG_VERSION:=$VERSION,g" "$GITHUB_WORKSPACE/Makefile"
        git add $GITHUB_WORKSPACE/Makefile
        git commit -m "Shadowsocks-Rust:bump to ${{ env.VERSION }}"
        git push

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 2
